apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ekscharts
  namespace: flux-system
spec:
  interval: 1m
  url: helm repo add eks https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appmesh
  namespace: appmesh-system
spec:
  interval: 5m
  chart:
    spec:
      chart: appmesh-controller
      sourceRef:
        kind: HelmRepository
        name: ekscharts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: 602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/aws-efs-csi-driver
      controller:
        serviceAccount:
          create: false
          name: appmesh-controller
