
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-privateca-issuer
  namespace: cert-manager
spec:
  interval: 1m
  releaseName: aws-privateca-issuer
  chart:
    spec:
      chart: aws-privateca-issuer
      sourceRef:
        kind: HelmRepository
        name: awspca
        namespace: flux-system
      interval: 1m
---
# apiVersion: awspca.cert-manager.io/v1beta1
# kind: AWSPCAClusterIssuer
# metadata:
#           name: demo-test-root-ca
# spec:
#           arn: <CA_ARN>
#           region: us-east-2