---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio
  namespace: rstudio
spec:
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio
        image: rocker/rstudio
        ports:
        - containerPort: 8787
      - name: haproxy
        image: public.ecr.aws/docker/library/haproxy:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: haproxy
            mountPath: /usr/local/etc/haproxy
            readOnly: true
      volumes:
        - name: haproxy
          configMap: 
            name: haproxy
            items:
              - key: haproxy.cfg
                path: haproxy.cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: rstudio
data:
  haproxy.cfg: |
    frontend haproxy
      mode http
      log global
      timeout client 30s
      bind *:8080
      default_backend rstudio
    backend rstudio
      mode http
      server s localhost:8787
---
 apiVersion: v1
kind: Service
metadata:
  name: rstudio-gateway
  namespace: rstudio
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-internal: (http://service.beta.kubernetes.io/aws-load-balancer-internal:) "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8088
      name: http
  selector:
    app: rstudio

