---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio
  namespace: rstudio
spec:
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio
        image: rocker/rstudio
        ports:
        - containerPort: 8787
      - name: haproxy
        image: public.ecr.aws/docker/library/haproxy:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: haproxy
            mountPath: /usr/local/etc/haproxy
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: haproxy
            items:
              - key: haproxy.cfg
                path: haproxy.cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
data:
  haproxy.cfg: |
    frontend haproxy
      mode http
      log global
      timeout client 30s
      bind: *:8080
      default_backend rstudio
    backend rstudio
      mode http
      server s localhost:8787




# apiVersion: appmesh.k8s.aws/v1beta2
# kind: VirtualNode
# metadata:
#   name: rstudio-appserver
#   namespace: rstudio
# spec:
#   awsName: rstudio-appserver
#   podSelector:
#     matchLabels:
#       app: rstudio
#   listeners:
#     - portMapping:
#         port: 8787
#         protocol: http  
#   serviceDiscovery:
#     dns:
#       hostname: rstudio.rstudio.svc.cluster.local
# ---
# apiVersion: appmesh.k8s.aws/v1beta2
# kind: VirtualRouter
# metadata:
#   namespace: rstudio
#   name: rstudio
# spec:
#   awsName: rstudio-virtual-router
#   listeners:
#     - portMapping:
#         port: 4567
#         protocol: http
#   routes:
#     - name: route-to-rstudio
#       httpRoute:
#         match:
#           prefix: /
#         action:
#           weightedTargets:
#             - virtualNodeRef: 
#                 name: rstudio-appserver
#               weight: 1
#         retryPolicy:
#             maxRetries: 2
#             perRetryTimeout:
#                 unit: ms
#                 value: 2000
#             httpRetryEvents:
#                 - server-error
#                 - client-error
#                 - gateway-error